server:
  port: 15000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
        transport:
            dashboard: localhost:8080
  application:
          name: gulimail-search
management:
  endpoints:
    web:
      exposure:
        include: '*'